### ISSUE TITLE
Missing Config FileWorker[18068] process terminated

### ISSUE THREAD

**Issue by imzlh** [joanhey/AdapterMan#13]
When I try to run it,I saw:
![error](https://user-images.githubusercontent.com/114276136/208643972-d9274ab3-301f-4e95-a0a3-6944ba792d11.png)
My source code:
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Adapterman\Adapterman;
use Workerman\Worker;

Adapterman::init();

$http_worker                = new Worker('http://0.0.0.0:8080');
$http_worker->count         = 1;
$http_worker->name          = 'typecho';

$http_worker->onWorkerStart = static function () {
    //init();
    require __DIR__.'/app/index.php';
};

$http_worker->onMessage = static function ($connection, $request) {

    $connection->send(run());
};

Worker::runAll();
Can you help me?Thanks.

**Comment by joanhey** [comment]
Which framework or app are you using ?

Do you catch all the Exceptions and errors?

But the error, looks very clear. 
Your app don't find the Config File.
It isn't a problem from Adapterman.

**Comment by joanhey** [comment]
I send a PR to prevent the confusion.

The error is:
`Missing Config File |> Worker[1084] process terminated`
