### ISSUE TITLE
An error occurred when using the Laravel framework under the daemon process

### ISSUE THREAD

**Issue by Neilyoz** [joanhey/AdapterMan#28]
PHP: 8.1.5
Laravel: 9.50.1
AdapterMan: dev-master

Workerman starts normally.

The first time I went to visit http://127.0.0.1:8080

![20230214115145](https://user-images.githubusercontent.com/57325053/218635076-bb788a81-5b58-4ead-993e-c138ef2531e0.png)

then I refresh
![20230214115156](https://user-images.githubusercontent.com/57325053/218635185-2973dab8-8f76-4982-9bfe-099085f617c3.png)

**Comment by joanhey** [comment]
Not all code and external libs, will work with Adapterman.

The same happen with Laravel Octane or Laravel Swoole.

The most important think is that the `Register` and `Boot` (and in more places) will be executed only 1 time.

More info:
https://laravel.com/docs/9.x/octane#dependency-injection-and-octane
https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues.md

**Comment by Neilyoz** [comment]
I found two problems and corresponding solutions in personal use.
1. StreamOutput error:
```
$http_worker->onMessage = static function ($connection, $request) {
    $_SERVER['VAR_DUMPER_FORMAT'] = 'server';
    $connection->send(run());
};
```
It works!

2.When using the grpc extension, you need to set grpc.enable_fork_support is set to 1; If you do not do this, the worker process will not be able to shut down. Of course, the probability of using grpc extension is relatively small.

I hope it can be helpful to the guys who encounter such problems in the future.
