### ISSUE TITLE
$_FILE support

### ISSUE THREAD

**Issue by jhdxr** [joanhey/AdapterMan#35]
For a native $_FILE from web server, the item should consist of `name`, `tmp_name`, `type`, `size` and `error`. However, AdapterMan provides `name`, `file_name`, `file_size` and `file_data` which doesn't actually match.

**Comment by joanhey** [comment]
Thanks, we will try to fix it.

Also we want to separate the code. At least the cookie and files part, to be outside from the http class.

**Comment by xini2603** [comment]
edit: http.php
rows:500

switch ($header_key) {
                    case "content-disposition":
                        // Is file data.
                        if (\preg_match('/name="(.*?)"; filename="(.*?)"/', $header_value, $match)) {
	                        $error = 0;
	                        $tmp_file = '';
	                        $file_name = $match[2];
	                        $size = \strlen($boundary_value);
	                        $tmp_upload_dir = \Workerman\Protocols\Http::uploadTmpDir();
	                        if (!$tmp_upload_dir) {
		                        $error = UPLOAD_ERR_NO_TMP_DIR;
	                        } else if ($boundary_value === '' && $file_name === '') {
		                        $error = UPLOAD_ERR_NO_FILE;
	                        } else {
		                        $tmp_file = \tempnam($tmp_upload_dir, 'workerman.upload.');
		                        if ($tmp_file === false || false === \file_put_contents($tmp_file, $boundary_value)) {
			                        $error = UPLOAD_ERR_CANT_WRITE;
		                        }
	                        }
	                        $upload_key = $match[1];
	                        // Parse upload files.
	                        $_FILES[$upload_key] = [
		                        'name' => $file_name,
		                        'tmp_name' => $tmp_file,
		                        'size' => $size,
		                        'error' => $error,
		                        'type' => '',
	                        ];
                            break;
                        } // Is post field.
                        else {
                            // Parse $_POST.
                            if (\preg_match('/name="(.*?)"$/', $header_value, $match)) {
                                //TODO search a fast solution
                                $post_encode_string .= urlencode($match[1]) . '=' . urlencode($boundary_value) . '&';
                            }
                        }
                        break;
                    case "content-type":
                        // add file_type
                        $_FILES[$upload_key]['type'] = \trim($header_value);
                        break;
                }

**Comment by joanhey** [comment]
The only important thing, is to maintain the simplicity of Workerman and Adapterman.

**Comment by jhdxr** [comment]
> Please, you can submit a PR. It's an Open Source project.
> I'm busy now.

I didn't submit the patch because it's merely a workaround, not a complete solution. e.g. I didn't perform any clean-up for the temporary files at all. In my opinion, it would be irresponsible to propose such PR.

I did have plans to contribute towards the reuse of HTTP from Workerman. That's why I proposed those modifications for the upstreams—to enhance comprehensiveness and simplify integration, including walkor/workerman#909. However, it's unlikely for me to continue those plans.

As you said, this is an OPEN SOURCE project, and I want to make it clear that I'm not making demands here. I'm simply offering my tech advice. As the creator, owner and maintainer of this project, you definitely have the sole right to make any decision.

**Comment by joanhey** [comment]
Process of a PR:
1. Submit it
2. Review
3. Make changes
4. Review again till ready
5. Merge

**Comment by joanhey** [comment]
An Open Source project, depends from the community.

**Comment by jhdxr** [comment]
It's not an obligation for community users to create PR, and you are not the only one feeling busy.

**Comment by joanhey** [comment]
Thank you and bye !!
