### ISSUE TITLE
Autoload src

### ISSUE THREAD

**Issue by dereuromark** [joanhey/AdapterMan#4]
```
    "autoload": {
        "psr-4": {
            "Adapterman\\": "/src"
        }
    }
```
should be
```
    "autoload": {
        "psr-4": {
            "Adapterman\\": "src/"
        }
    }
```
!

See e.g. https://github.com/cakephp/cakephp/blob/4.x/composer.json#L79

**Comment by joanhey** [comment]
Thank you.

I'll change it, but it's working so.

**Comment by joanhey** [comment]
In reality is only used 1 time with Workerman.
As all files finish persistent in RAM.

**Comment by joanhey** [comment]
Thank you again !!
