### ISSUE TITLE
WordPress support?

### ISSUE THREAD

**Issue by accuretix** [joanhey/AdapterMan#50]
Hello @joanhey 

I know this is probably a hot/hard ask, but would it be possible to have WordPress support or would it be requiring changes to the WordPress core?

**Comment by joanhey** [comment]
Absolutely it need changes in the Wordpress Core.

**Comment by ray929** [comment]
> Absolutely it need changes in the Wordpress Core, to work as persistent app (worker mode).
> 
> With the shared mode nothing, it will work. But this mode is experimental, and still we didn't get a good performance from it.

Is there any progress?
Thank u
