### ISSUE TITLE
When I run in laravel, it throw exception: Class Redis not found?

### ISSUE THREAD

**Issue by mouyong** [joanhey/AdapterMan#6]
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/10336437/207640858-33f39f6c-2c38-4392-a45b-0f26266ddb22.png">

<img width="783" alt="image" src="https://user-images.githubusercontent.com/10336437/207641107-a778c4eb-b808-402a-b7a5-d1153a33aded.png">

php.ini content: https://github.com/joanhey/AdapterMan/blob/master/cli-php.ini

**Comment by mouyong** [comment]
Laravel config/database.php: redis client is phpredis.

Laravel Cache use redis cache.

**Comment by joanhey** [comment]
Had you added redis to the php.ini that you send with the `-c` option.
If Redis is in `/etc/php/x.x/cli/conf.d/` dir, will be loaded automatically.

If it's added in the `/etc/php/x.x/cli/php.ini` , and you use another `php.ini`, you need to add to that one.

**Comment by mouyong** [comment]
you are right. When I use php -c php.ini, I need add `extension = /path/to/redis.so` in php.ini

**Comment by joanhey** [comment]
If you create in `/etc/php/x.x/cli/conf.d/redis.ini`, with `extension = /path/to/redis.so`.
Will be loaded automatically.

**Comment by joanhey** [comment]
Also if you use Workerman, and only 1 server, we can create a Workerman cache.
And we don't need Redis for cache.

**Comment by joanhey** [comment]
And without the `-c` option, will use your normal `cli/php.ini`.
With all your extensions and configs.

**Comment by mouyong** [comment]
maybe you are right. add `redis.so` to php.ini.
