### ISSUE TITLE
thinkphp fix More Load Middleware File

### ISSUE THREAD

**Issue by 645418484** [joanhey/AdapterMan#69]

**Comment by 645418484** [comment]
I tried to connect with thinkphp and found that the first request worked and subsequent requests always got an error
![image](https://github.com/joanhey/AdapterMan/assets/38717760/d033c378-4c80-41e7-adbf-7807fb8f3bd4)

**Comment by 645418484** [comment]
pr #68

**Comment by joanhey** [comment]
@yangguangwuwu Could you check it ??
Thanks

**Comment by yangguangwuwu** [comment]
> @yangguangwuwu Could you check it ?? Thanks

code   ok

**Comment by yangguangwuwu** [comment]
Pull requests can be merged.
