### ISSUE TITLE
post data can not be obtained, is something wrong?

### ISSUE THREAD

**Issue by dunkong** [joanhey/AdapterMan#74]
Thanks to the author for providing this good project, which solved a big problem for me, but I couldn't get the post data during the use process, and there was no data in print request()->all(). I used laravel9, is there anything that needs special attention, thank you very much

**Comment by joanhey** [comment]
Please read https://github.com/joanhey/AdapterMan/issues/66#issuecomment-1913545482

Adapterman have a large set of tests, including POST data without problems.


If you still have problems after read the recommendations, please comment again here.

**Comment by dunkong** [comment]
> Please read [#66 (comment)](https://github.com/joanhey/AdapterMan/issues/66#issuecomment-1913545482)
> 
> Adapterman have a large set of tests, including POST data without problems. So the problem will be in the implementation used in Laravel.
> 
> If you still have problems after read the recommendations, please comment again here.

Of course, I think this is a problem of my own use, not an AdapterMan problem, but I really can't find any reason for it, and I also see the same issue. I am very sorry if I have bothered you

**Comment by joanhey** [comment]
Please read:
https://laravel.com/docs/10.x/octane#dependency-injection-and-octane

The same happens with Adapterman.
