### ISSUE TITLE
Does this bundle support symonfy7?

### ISSUE THREAD

**Issue by Mickeywaugh** [joanhey/AdapterMan#80]
Does this bundle support symonfy7?
I think the answer should be "Yes",but how to write the start.php for symfony7?

**Comment by joanhey** [comment]
Of course, and the `start.php` work for both Symfony 6 and 7, without any change.
We didn't test it with older versions.

And the same Laravel `start.php` work with Laravel 8, 9, 10 and 11.

To maintain the Techempower benchmark, we update it regularly with the new PHP frameworks versions.
Til now, we never had to change the `start.php` or Adapterman. 

But we need to change the code use it for the framework, to adapt to the new version for work with PHP-FPM or any other SAPI.
