### ISSUE TITLE
Error: Recursion detected in ThinkPHP 8.0

### ISSUE THREAD

**Issue by binbin014** [joanhey/AdapterMan#83]
<img width="1303" alt="image" src="https://github.com/user-attachments/assets/0c419180-a698-475f-8416-55aaa2099efc">

**Comment by joanhey** [comment]
Hi, @binbin014 
Sorry but I think that this problem is NOT from Adapterman.

It's a problem with `json_encode() `with recursive structures.
If you still think that is from Adapterman, please give more information or part of the code with the problem.
